services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    restart: always
    command: gunicorn -b 0.0.0.0:80 cas.wsgi:application
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=paras
      - DB_USER=paras
      - DB_PASSWORD=1212

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: paras
      POSTGRES_USER: paras
      POSTGRES_PASSWORD: 1212
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

volumes:
  postgres_data:
