# Generated by Django 5.1.3 on 2024-11-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_customer_id_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
